postgres_dsn = "host=localhost user=postgres password=123456 dbname=postgres port=45433 sslmode=disable TimeZone=Europe/Berlin"

twitch_nick = "justinfan30316"
twitch_user = "justinfan30316"
twitch_name = "justinfan30316"
twitch_pass = "justinfan30316"

web_bind = ":30001" # used for ping