PostgresHost = "localhost"
PostgresUser = "postgres"
PostgresPass = "123456"
PostgresDb = "postgres"
PostgresPort = "45433"
PostgresTZ = "Europe/Berlin"

TwitchNick = "justinfan30316"
TwitchUser = "justinfan30316"
TwitchName = "justinfan30316"
TwitchPass = "justinfan30316"

SentryDSN = ""

WebBind = ":30001" # used for ping